//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendOfFall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogPost()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string AuthorName { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
