//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendOfFall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> BlogPostId { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public string Path { get; set; }
        public Nullable<bool> DisplayOnMain { get; set; }
        public Nullable<int> JudgeId { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual BlogPost BlogPost { get; set; }
        public virtual Season Season { get; set; }
    }
}
